### PR TITLE
changed RetrySupport.withRetry implementation to use @tailrec under t…

### PR DESCRIPTION
**Pull request by sha1n**
changed `RetrySupport.withRetry(...)` implementation to use `@tailrec` under the hood in order to avoid unnecessary long stacks

### CODE REVIEW

**Comment by ittaiz** [comment]
@sha1n you previously said you're afraid you'll break the API, why?
Want to make sure there isn't a caveat I'm missing but other than that it looks ok.

**Comment by sha1n** [comment]
@ittaiz I ended up implementing it in a backward compatible way. If you remember, I suggested that as a solution...

**Comment by ittaiz** [comment]
I actually don't remember but great!

Just to verify the build passes with your change, right?



—

**Comment by sha1n** [comment]
@ittaiz If you mean the framework then honestly I don't remember, but I think it does. There are no signature changes or visibility changes here, so...

**Comment by ittaiz** [comment]
I meant future perfect itself



—

**Pull request merged**
